server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/fangzydb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 500MB
      location: /home/fzy/tmp
      max-request-size: 500MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
    aop:
      proxy-target-class: true
      auto: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true

kbase:
  driverclass: com.kbase.jdbc.Driver
  url: jdbc:kbase://10.140.128.128:4567
  username: dbown
  password:
  coverPath: 124.193.98.166:8386      # 书籍相关附件IP
filePath: /home/fzy/recordFile
