server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://124.193.98.166:8385/fangzydb
    password: jonespost
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 500MB
      location: /home/xiangjg/tmp/
      max-request-size: 500MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
  aop:
    proxy-target-class: true
    auto: true
# KBase
kbase:
  driverclass: com.kbase.jdbc.Driver
  url: jdbc:kbase://127.0.0.1:4567
  username: dbown
  password:
#  file
filePath: /home/xiangjg/file
